spring.application.name=coppetec--chat

#mssql
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USER_SA}
spring.datasource.password=${DATASOURCE_PASSWORD_SA}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2008Dialect

#eureka
eureka.client.serviceUrl.defaultZone=${EUREKA_URL}


host.aplicacao=http://localhost:5174/